spring:
  application:
    name: level-up-backend

  cloud:
    config:
      name: levelup

  config:
    import: optional:configserver:http://43.200.179.145:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #actuator 설정실패 때문에 삽입

logging:
  config: classpath:log4j2-prod.xml