spring:
  application:
    name: level-up-backend

  cloud:
    config:
      name: levelup

  sql:
    init:
      mode: NEVER

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  config:
    import: optional:configserver:http://localhost:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #actuator 설정실패 때문에 삽입

logging:
  config: classpath:log4j2-dev.xml
