version: '3'

services:
  mysql:
    container_name: level-up-mysql
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: level_up
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - level-up-network
  redis:
    container_name: level-up-redis
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    networks:
      - level-up-network

networks:
  level-up-network:
    driver: bridge
