version: '3'

services:
  mysql:
    container_name: level-up-recruit
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "Dudrhkd10ck!"
    ports:
      - "3309:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"