server:
  port: 8090

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  sql:
    init:
      mode: NEVER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/level_up?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #actuator 설정실패 때문에 삽입

  mail:
    username: koria789@gmail.com
    password: dlxpnbkbcbaorjuh
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

jasypt:
  encryptor:
    bean: encryptorBean

#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

file:
  storage:
    dir: D:/personal/project/level-up/source/backend/level-api/src/main/resources/storage
