server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE
      timeout: 1800

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/level_up?serverTimezone=Asia/Seoul
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  mail:
    username: koria789@gmail.com
    password: dlxpnbkbcbaorjuh
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    cache: false
    prefix: file:level-api/src/main/resources/templates/

  application:
    name: level-up-backend

  cloud:
    config:
      name: levelup

  sql:
    init:
      mode: never

  jpa:
    database-platform: com.levelup.common.config.MySQL8DialectCustom
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password: ''

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #actuator 설정실패 때문에 삽입

jasypt:
  encryptor:
    bean: encryptorBean

file:
  storage:
    dir: C:/Task/project/level-up/storage

#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
