server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE
      timeout: 1800

spring:
  thymeleaf:
    cache: false
    prefix: file:level-api/src/main/resources/templates/

  application:
    name: level-up-backend

  cloud:
    config:
      name: levelup

  sql:
    init:
      mode: NEVER

  jpa:
    database-platform: com.levelup.common.config.MySQL8DialectCustom
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    password: ''

  config:
    import: optional:configserver:http://localhost:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #actuator 설정실패 때문에 삽입

logging:
  config: classpath:log4j2-dev.xml

file:
  local_dir: C:/Task/study/levelup
  s3_dir: https://mylevelupbuckets3.s3.ap-northeast-2.amazonaws.com

#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh